### ISSUE TITLE
cities can not be traded with teammates

### ISSUE THREAD

**Issue by HackYardo** [pbatr/Civ4-Reimagined#9]
This new feature of version 2.0, "cities can not be traded unless at war", is a bit weird. Civ series games are time-hunger, to play a whole game from begin to end needs **tons of hours**. So I organize bots into teams before game start usually. And then trade cities with a bot teammate to save the time of managing cities.

**Comment by pbatr** [comment]
City trading during peace time is a bit of a weird and unhistoric mechanic and can be easily abused especially in multiplayer. That's why we decided to remove it (you can still liberate cities which you previously conquered from a different civ). Your style of play sounds quite unique to be honest. I would suggest to fix it on your own. You can fork this repository and then the change should be quite simple.
